<?php
$app_date = date("m/d/Y h:i:s e");
$pdf->AddPage();
$pdf->SetFont('Helvetica','',$pdf->font_size);
$pdf->heading("Application submitted " . $app_date);
$pdf->print_line("Name",$post['uk_name']);
$pdf->print_line("Address",$post['uk_address'], true);
$pdf->print_line("Telephone (daytime)",$post['uk_telephone_daytime']);
$pdf->print_line("Telephone (mobile)",$post['uk_telephone_mobile']);
$pdf->print_line("Email",$post['uk_email']);

$pdf->heading("Education");
$pdf->print_line("From (mm/yy)",$post['uk_education_from_1']);
$pdf->print_line("To (mm/yy)",$post['uk_education_to_1']);
$pdf->print_line("Name of Institution",$post['uk_education_institution_1']);
$pdf->print_line("Subject & Grade",$post['uk_education_subject_1']);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_education_from_2']);
$pdf->print_line("To (mm/yy)",$post['uk_education_to_2']);
$pdf->print_line("Name of Institution",$post['uk_education_institution_2']);
$pdf->print_line("Subject & Grade",$post['uk_education_subject_2']);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_education_from_3']);
$pdf->print_line("To (mm/yy)",$post['uk_education_to_3']);
$pdf->print_line("Name of Institution",$post['uk_education_institution_3']);
$pdf->print_line("Subject & Grade",$post['uk_education_subject_3']);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_education_from_4']);
$pdf->print_line("To (mm/yy)",$post['uk_education_to_4']);
$pdf->print_line("Name of Institution",$post['uk_education_institution_4']);
$pdf->print_line("Subject & Grade",$post['uk_education_subject_4']);
$pdf->heading("Work Experience");
$pdf->print_line("From (mm/yy)",$post['uk_work_from_1']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_1']);
$pdf->print_line("Employer",$post['uk_work_employer_1'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_1'], true);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_work_from_2']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_2']);
$pdf->print_line("Employer",$post['uk_work_employer_2'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_2'], true);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_work_from_3']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_3']);
$pdf->print_line("Employer",$post['uk_work_employer_3'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_3'], true);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_work_from_4']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_4']);
$pdf->print_line("Employer",$post['uk_work_employer_4'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_4'], true);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_work_from_5']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_5']);
$pdf->print_line("Employer",$post['uk_work_employer_5'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_5'], true);
$pdf->Ln();
$pdf->print_line("From (mm/yy)",$post['uk_work_from_6']);
$pdf->print_line("To (mm/yy)",$post['uk_work_to_6']);
$pdf->print_line("Employer",$post['uk_work_employer_6'], true);
$pdf->print_line("Nature of Employment",$post['uk_work_nature_6'], true);
$pdf->Ln();
$pdf->essay_question("Please provide an example of an activity or event that required you to work as part of a team to achieve a particular objective.  What was this activity, your role and the key learnings?",$post['uk_essay_1']);
$pdf->essay_question("In terms of leadership skills, who has personally inspired you and why.  This could be either someone you know or a public figure.",$post['uk_essay_2']);
$pdf->essay_question("If you were successful in your application, what would you like to achieve by the end of the 9 months?",$post['uk_essay_3']);
$pdf->heading("Practice area preference");
$pdf->print_line("Consumer",$post['uk_pref_consumer'], false, 80);
$pdf->print_line("Digital",$post['uk_pref_digital'], false, 80);
$pdf->print_line("Ethical Healthcare & Medical Education",$post['uk_pref_healthcare'], false, 80);
$pdf->print_line("Public Affairs & Corporate",$post['uk_pref_public_affairs'], false, 80);
$pdf->print_line("Technology",$post['uk_pref_technology'], false, 80);
$pdf->print_line("Financial Services",$post['uk_pref_financial_services'], false, 80);
$pdf->heading("Referrals");
$pdf->print_line("Title",$post['uk_referral_title_1']);
$pdf->print_line("Surname",$post['uk_referral_surname_1']);
$pdf->print_line("First Name",$post['uk_referral_first_name_1']);
$pdf->print_line("Occupation",$post['uk_referral_occupation_1']);
$pdf->print_line("Relationship to applicant",$post['uk_referral_relationship_1']);
$pdf->print_line("Address",$post['uk_referral_address_1'], true);
$pdf->print_line("Telephone",$post['uk_referral_telephone_1']);
$pdf->print_line("Fax",$post['uk_referral_fax_1']);
$pdf->print_line("Email",$post['uk_referral_email_1']);
$pdf->Ln();
$pdf->print_line("Title",$post['uk_referral_title_2']);
$pdf->print_line("Surname",$post['uk_referral_surname_2']);
$pdf->print_line("First Name",$post['uk_referral_first_name_2']);
$pdf->print_line("Occupation",$post['uk_referral_occupation_2']);
$pdf->print_line("Relationship to applicant",$post['uk_referral_relationship_2']);
$pdf->print_line("Address",$post['uk_referral_address_2'], true);
$pdf->print_line("Telephone",$post['uk_referral_telephone_2']);
$pdf->print_line("Fax",$post['uk_referral_fax_2']);
$pdf->print_line("Email",$post['uk_referral_email_2']);
		  
	

?>